name: CI & CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest requests pytest-cov python-dotenv

      - name: Testes unitários
        run: pytest backend/tests --cov=backend

      - name: Testes end-to-end online
        env:
          TEST_PROF_EMAIL: ${{ secrets.TEST_PROF_EMAIL }}
          TEST_PROF_PASS:  ${{ secrets.TEST_PROF_PASS }}
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
        run: pytest online_test.py -q

      - name: Instalar Flyctl CLI
        if: github.ref == 'refs/heads/main'
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy no Fly.io
        if: github.ref == 'refs/heads/main'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --config fly.toml --remote-only

